In [9]:
import numpy as np

a1 = np.array([8, 9, 38, 7, 5])
a2 = np.array([11, 2, 64, 11, 5])
print("Original numbers:")
print(a1)
print(a2)
print("Comparison - greater")
print(np.greater(a1, a2))
print("Comparison - greater_equal")
print(np.greater_equal(a1, a2))
print("Comparison - less")
print(np.less(a1, a2))
print("Comparison - less_equal")
print(np.less_equal(a1, a2))

Original numbers:
[ 8  9 38  7  5]
[11  2 64 11  5]
Comparison - greater
[False  True False False False]
Comparison - greater_equal
[False  True False False  True]
Comparison - less
[ True False  True  True False]
Comparison - less_equal
[ True False  True  True  True]


In [15]:
even = [x for x in range(30,70) if x%2 == 0]
print(even)

[30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68]


In [19]:
import numpy as np
a=np.eye(3,dtype="int64")
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [21]:
import numpy as np
v=np.arange(21)
v[(v>=9) & (v<=15)]*=-1
print(v)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [27]:
import numpy as np
v=np.eye(5,dtype="int64")
np.fill_diagonal(v,[1,2,3,4,5])
print(v)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [29]:
import numpy as np
a = np.matrix('50 10; 70 80;30 90;65 44')
print("Original matrix: \n", a)
print("\nThe sum of the matrix is: ", np.sum(a))
sum_of_rows = np.sum(a, axis = 0)
print("\nSum of all the rows: ", sum_of_rows)

sum_of_cols = np.sum(a, axis = 1)
print("\nSum of all the columns: \n", sum_of_cols)

Original matrix: 
 [[50 10]
 [70 80]
 [30 90]
 [65 44]]

The sum of the matrix is:  439

Sum of all the rows:  [[215 224]]

Sum of all the columns: 
 [[ 60]
 [150]
 [120]
 [109]]


In [21]:
import numpy as np
import os
x = np.arange(12).reshape(3, 4)
print("Original array:")
print(x)
file=open("textfile.txt","w")
c=str(x)
file.write(c)
file.close()
file=open("textfile.txt","r")
print("After loading, content of the text file:\n",file.read())
file.close();

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
After loading, content of the text file:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [39]:
import numpy as np
a1=np.array([33,22,34,54,23])
a2=np.array([10,20,30,40,50])
print(np.array_equal(a1,a2))

False


In [19]:
import numpy as np
random_array=np.random.randint(10,size=(4,4))
print("Original array:")
print(random_array)
print("\n")
random_array[[0,-1],:]=random_array[[-1,0],:]
print(random_array)

Original array:
[[5 9 1 5]
 [4 2 0 3]
 [8 9 4 9]
 [3 5 4 4]]


[[3 5 4 4]
 [4 2 0 3]
 [8 9 4 9]
 [5 9 1 5]]


In [28]:
import numpy as np
a1 = np.array([8, 9, 8, 7, 5])
a2 = np.array([11, 20, 10, 11, 5])
print(a1)
print(a2,"\n")
a3=np.multiply(a1,a2)
print(a3)

[8 9 8 7 5]
[11 20 10 11  5] 

[ 88 180  80  77  25]
